import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import Menu from "@/components/menu";

const soraSans = Sora({
  variable: "--font-sora-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${soraSans.variable} font-sora-sans antialiased`}>
        <Menu />
        {children}
      </body>
    </html>
  );
}
